lsst-distrib: Distinguish update vs install

diff --git a/bin/lsst-distrib b/bin/lsst-distrib
--- a/bin/lsst-distrib
+++ b/bin/lsst-distrib
@@ -1,27 +1,56 @@
 #!/bin/bash
 #
-# bash install.sh [dest_dir]
+# See usage() for documentation
 #
 
-if [[ $# > 2 || $1 == "--help" || $1 == "-h" ]]; then
-	cat <<-EOF;
-		Usage: $0 [destdir]
+set -e
+DEFROOT=/opt/lsst
 
+usage()
+{
+	cat <<-EOF;
 		Clones a pre-built binary distribution of the LSST Data Management
 		Software Stack.
 	
+		Usage:
+		
+		        $0 [-h|--help] [update|install] [dest_dir]
+
+		Running with no command line arguments is equivalent to running
+		'$0 install'.
+
+		Arguments:
+		install		Install the binary distribution of DM stack
+		update		Update an existing binary distribution install
+
 		dest_dir	EXPERIMENTAL: Install the stack to <destdir>, rather
 		                than the directory it was originally built in. This
 		                is an experimental feature and may cause some
 		                misbehavior.
 EOF
-	exit;
-fi
+	exit -2;
+}
 
-DEFROOT=/opt/lsst
-ROOT=${1-$DEFROOT}
+[[ $1 == "--help" || $1 == "-h" ]] && usage
 
-set -e
+MODE="$1"
+case "$MODE" in
+install|"")
+	ROOT=${2-$DEFROOT}
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Have you forgotten to run this script as root?"; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Have you forgotten to run this script as root?"; exit -1; }
+	[[ -e $ROOT && ! -z $(ls -A "$ROOT") ]] && { echo "$ROOT already has some content; did you mean to run '$0 update'?."; exit -1; }
+	;;
+update)
+	ROOT=${2-$DEFROOT}
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Have you forgotten to run this script as root?"; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Have you forgotten to run this script as root?"; exit -1; }
+	;;
+*)
+	usage
+esac
+
+ROOT=$(cd "$ROOT" && pwd)
 
 detectOS()
 {
@@ -79,10 +108,6 @@ checkPrereq()
 	esac
 }
 
-mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Have you forgotten to run this script as root?"; exit -1; }
-[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Have you forgotten to run this script as root?"; exit -1; }
-ROOT=$(cd "$ROOT" && pwd)
-
 OS=$(detectOS)
 NAME="dmstack-$OS"
 URLBASE="rsync://moya.dev.lsstcorp.org/dmstack"
@@ -106,6 +131,7 @@ if [[ $ROOT != "$DEFROOT" ]]; then
 	( cd "$ROOT" && grep -Rl --exclude '*.pyc' --exclude '*~' "$DEFROOT" eups loadLSST.* | xargs sed -i \~ "s|$DEFROOT|$ROOT|" )
 fi
 
+if [[ $MODE == "install" ]]; then
 cat <<-EOF;
 
 	Done. The LSST Data Management stack has been installed in:
@@ -122,3 +148,4 @@ cat <<-EOF;
 
 	to load version management with EUPS and begin using it.
 EOF
+fi
