lsst-distrib: errors should go to stderr
Bug reported by Petr Kubanek.

diff --git a/bin/lsst-distrib b/bin/lsst-distrib
--- a/bin/lsst-distrib
+++ b/bin/lsst-distrib
@@ -8,7 +8,7 @@ URLBASE=${DISTRIB_URL-"rsync://moya.dev.lsstcorp.org/dmstack"}
 
 usage()
 {
-	cat <<-EOF;
+	cat 1>&2 <<-EOF;
 		Clones a pre-built binary distribution of the LSST Data Management
 		Software Stack.
 	
@@ -55,12 +55,12 @@ detectOS()
 			OS="rhel"
 			VER=$(cat /etc/redhat-release | sed -r 's/^.[^0-9.]*([0-9]*).*$/\1/')
 		else
-			echo "Unknown Linux flavor; please install from source."
+			echo "Unknown Linux flavor; please install from source." 1>&2
 			exit -1
 		fi
 		;;
 	*)
-		echo "Unsupported operating system. Try installing from source"
+		echo "Unsupported operating system. Try installing from source" 1>&2
 		exit -1
 		;;
 	esac
@@ -84,9 +84,9 @@ checkPrereq()
 			rpm --quiet -q "$rpm.$MACH" || { MISSING_RPMS="$MISSING_RPMS $rpm"; }
 		done
 		if [[ ! -z $MISSING_RPMS ]]; then
-			echo "Missing prerequisites: $MISSING_RPMS"
-			echo "As root, run:"
-			echo "    yum install $MISSING_RPMS"
+			echo "Missing prerequisites: $MISSING_RPMS" 1>&2
+			echo "As root, run:" 1>&2
+			echo "    yum install $MISSING_RPMS" 1>&2
 			exit -1
 		fi
 		;;
@@ -98,9 +98,9 @@ checkPrereq()
 			rpm --quiet -q "$rpm.$MACH" || { MISSING_RPMS="$MISSING_RPMS $rpm"; }
 		done
 		if [[ ! -z $MISSING_RPMS ]]; then
-			echo "Missing prerequisites: $MISSING_RPMS"
-			echo "As root, run:"
-			echo "    yum install $MISSING_RPMS"
+			echo "Missing prerequisites: $MISSING_RPMS" 1>&2
+			echo "As root, run:" 1>&2
+			echo "    yum install $MISSING_RPMS" 1>&2
 			exit -1
 		fi
 		;;
@@ -192,14 +192,14 @@ fi
 case "$1" in
 install)
 	MODE=install
-	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions?"; exit -1; }
-	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
-	[[ -e $ROOT && ! -z $(ls -A "$ROOT") ]] && { echo "$ROOT already has some content; did you mean to run '$CMD update'?."; exit -1; }
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions?" 1>&2; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?" 1>&2; exit -1; }
+	[[ -e $ROOT && ! -z $(ls -A "$ROOT") ]] && { echo "$ROOT already has some content; did you mean to run '$CMD update'?." 1>&2; exit -1; }
 	;;
 update)
 	MODE=update
-	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions??"; exit -1; }
-	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions??" 1>&2; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?" 1>&2; exit -1; }
 	;;
 *)
 	usage
