lsst-distrib: Enhanced install logic (now ROOT=/opt/lsst/$OS)

diff --git a/bin/lsst-distrib b/bin/lsst-distrib
--- a/bin/lsst-distrib
+++ b/bin/lsst-distrib
@@ -4,10 +4,7 @@
 #
 
 set -e
-DEFROOT=${LSST_HOME-/opt/lsst}
 URLBASE="rsync://moya.dev.lsstcorp.org/dmstack"
-
-CMD=$(basename "$0")
 
 usage()
 {
@@ -43,28 +40,6 @@ EOF
 	exit -2;
 }
 
-[[ $1 == "--help" || $1 == "-h" ]] && usage
-
-case "$1" in
-install)
-	MODE=install
-	ROOT=${2-$DEFROOT}
-	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions?"; exit -1; }
-	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
-	[[ -e $ROOT && ! -z $(ls -A "$ROOT") ]] && { echo "$ROOT already has some content; did you mean to run '$CMD update'?."; exit -1; }
-	;;
-update)
-	MODE=update
-	ROOT=${2-$DEFROOT}
-	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions??"; exit -1; }
-	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
-	;;
-*)
-	usage
-esac
-
-ROOT=$(cd "$ROOT" && pwd)
-
 detectOS()
 {
 	OS=$(uname)
@@ -77,7 +52,7 @@ detectOS()
 		;;
 	"Linux")
 		if [ -f /etc/redhat-release ]; then
-			OS="rhel_compatible"
+			OS="rhel"
 			VER=$(cat /etc/redhat-release | sed -r 's/^.[^0-9.]*([0-9]*).*$/\1/')
 		else
 			echo "Unknown Linux flavor; please install from source."
@@ -95,7 +70,7 @@ checkPrereq()
 	[[ $CHECK_PREREQ == 0 ]] && return 0
 
 	case $OS in
-	rhel_compatible-6-*)
+	rhel-6-*)
 		for rpm in rsync gcc-c++ gcc-gfortran flex bison tk-devel \
 			   libXt-devel ncurses-devel readline-devel \
 			   libuuid-devel zlib-devel bzip2-devel perl make; \
@@ -109,7 +84,7 @@ checkPrereq()
 			exit -1
 		fi
 		;;
-	rhel_compatible-5-*)
+	rhel-5-*)
 		for rpm in which perl make gcc-c++ flex bison libX11-devel tk-devel \
 			   readline-devel zlib-devel gcc44-c++ gcc44-gfortran \
 			   e2fsprogs-devel bzip2-devel libXt-devel libstdc++44-devel; \
@@ -129,7 +104,7 @@ checkPrereq()
 getAvailableStacks()
 {
 	echo $(rsync $1 -n  | grep "^d" | grep -v ".* \.$" | awk '{print $5}')
-	##echo "osx-10.7-x86_64 osx-10.8-x86_64 rhel_compatible-6-x86_64"
+	##echo "osx-10.7-x86_64 osx-10.8-x86_64 rhel-6-x86_64"
 }
 
 containsElement()
@@ -139,15 +114,25 @@ containsElement()
 	return 1
 }
 
-# Detect OS, ask user for confirmation if it's different from what's stored in
-# $ROOT/.os
+###########
+
+CMD=$(basename "$0")
 OS=$(detectOS)
-STACKS=( $(getAvailableStacks "$URLBASE") )
-containsElement "$OS" "${STACKS[@]}" && SUPP="supported" || SUPP="UNSUPPORTED"
+
+[[ $1 == "--help" || $1 == "-h" ]] && usage
+containsElement "$1" install update || usage
+
+[[ -z "$LSST_HOME" ]] && unset LSST_HOME
+DEFROOT=${LSST_HOME-/opt/lsst/$OS}
+ROOT=${2-$DEFROOT}
+
+# Detect OS, ask for confirmation if it's different from what's stored in $ROOT/.os
 test -f "$ROOT/.os" && OS_STORED=$(head -n 1 "$ROOT/.os")
 if [[ $OS != $OS_STORED ]]; then
+	STACKS=( $(getAvailableStacks "$URLBASE") )
+	containsElement "$OS" "${STACKS[@]}" && SUPP="supported" || SUPP="UNSUPPORTED"
 	while true; do
-		echo    "Install version for which platform?"
+		echo    "Install version for which platform (destination: $ROOT)?"
 		echo    "   Available platforms: ${STACKS[@]}"
 		echo    "   Detected platform:   $OS ($SUPP)"
 		read -p "Enter platform, press ENTER to use '$OS', or CTRL-C to quit: " os
@@ -162,13 +147,53 @@ if [[ $OS != $OS_STORED ]]; then
 			break
 		fi
 	done
+	echo
+
 	OS="$os"
+	DEFROOT=${LSST_HOME-/opt/lsst/$OS}
+	ROOT=${2-$DEFROOT}
+
+	# If there's a mismatch with what's in $ROOT/.os, ask for confirmation
+	if [[ -f "$ROOT/.os" ]]; then
+		OS_STORED=$(head -n 1 "$ROOT/.os")
+		if [[ $OS != $OS_STORED ]]; then
+			while true; do
+				echo "You've elected to install the distribution for platform $OS, but the" \
+				     "directory to which you're installing contains binaries for $OS_STORED."
+				read -p "Are you sure you want to continue (y/n)? " yn
+				case $yn in
+					[Yy]* ) break;;
+					[Nn]* ) echo "Quitting."; exit -1;;
+					* ) echo "Please answer yes or no.";;
+				esac
+			done
+		fi
+	fi
 fi
+
+# Decide on mode of operation
+case "$1" in
+install)
+	MODE=install
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions?"; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
+	[[ -e $ROOT && ! -z $(ls -A "$ROOT") ]] && { echo "$ROOT already has some content; did you mean to run '$CMD update'?."; exit -1; }
+	;;
+update)
+	MODE=update
+	mkdir -p "$ROOT" || { echo "Failed to create $ROOT. Do you have the necessary permissions??"; exit -1; }
+	[[ -w "$ROOT" ]] || { echo "$ROOT is not writable. Do you have permissions to write there?"; exit -1; }
+	;;
+*)
+	usage
+esac
+
+ROOT=$(cd "$ROOT" && pwd)
+echo "Installing to $ROOT"
 
 checkPrereq "$OS"
 
 URL="$URLBASE/$OS/"
-echo "Installing to $ROOT"
 echo "Downloading using rsync from $URL"
 n=0
 while read line; do
